version: '3.8'

services:
  mysql_db:
    container_name: database
    image: cytopia/mysql-5.6
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: {}
